---
threescale_route_suffix: ""

#SSO
threescale_sso_namespace: "{{ eval_rhsso_namespace | default('sso') }}"
threescale_sso_admin_username: admin
threescale_sso_admin_realm: master
threescale_sso_realm: openshift
threescale_sso_validate_certs: "{{ eval_sso_validate_certs | default('true') }}"
threescale_oauth_client_id: 3scale

#Resource limits
threescale_limit_range_name: 3scale-core-resource-limits
threescale_limit_range_container_default_cpu: 500m
threescale_limit_range_container_default_memory: 1536Mi
threescale_limit_range_container_default_request_cpu: 50m
threescale_limit_range_container_default_request_memory: 256Mi
threescale_limit_range_container_max_memory: 32Gi
threescale_limit_range_container_min_memory: 10Mi
threescale_limit_range_pod_max_memory: 32Gi
threescale_limit_range_pod_min_memory: 6Mi

#Users
rhsso_evals_admin_email: customer-admin@example.com
rhsso_evals_admin_username: customer-admin

rhsso_seed_users_email_format: evals%02d@example.com
rhsso_seed_users_name_format: evals%02d
rhsso_seed_users_count: "{{ eval_seed_users_count }}"
rhsso_seed_users_password: Password1

threescale_cluster_admin_username: customer-admin
threescale_cluster_admin_old_username: admin

#Template Params
threescale_pvc_rwx_storageclassname: efs

threescale_master_access_token_secret_name: 3scale-master-access-token

enable_wildcard_route: false
wildcard_policy_param: ""

# Backups
threescale_backup_mysql_secret: threescale-mysql-secret
threescale_backup_postgres_secret: threescale-postgres-secret
threescale_backup_redis_secret: threescale-redis-secret

threescale_pull_secret_name: "threescale-registry-auth"

threescale_resources:
 - name: backend-redis
   kind: dc
   resources:
     limits:
       memory: 0
 - name: system-redis
   kind: dc
   resources:
     limits:
       memory: 0

# Routes
threescale_route_system_developer: system-developer
threescale_route_system_master: system-master
threescale_route_system_provider: system-provider

threescale_image_streams:
  - amp-apicast:latest
  - amp-backend:latest
  - amp-system:latest
  - amp-zync:latest
  - zync-database-postgresql:latest
  - system-mysql:latest
  - system-memcached:latest
  - system-redis:latest
  - backend-redis:latest

threescale_heimdall_exclude_pattern: ""
