---
- name: "Set facts required to patch the middleware-monitoring"
  set_fact:
    monitoring_upgrade_namespace: "{{ eval_middleware_monitoring_namespace }}"

- name: "Export the prometheus rules in ksm-alerts"
  shell: "oc get prometheusrules ksm-alerts -o yaml --namespace {{ monitoring_upgrade_namespace }} > /tmp/ksm-alerts.yml"
  register: export_prometheusrules
  failed_when: export_prometheusrules.stderr != ''

- name: "Find/replace exported_pod with pod in ksm-alerts prometheus rules"
  shell: "sed -i 's/exported_pod/pod/g' /tmp/ksm-alerts.yml"
  register: sed_prometheusrules
  failed_when: sed_prometheusrules.stderr != ''

- name: "Apply the prometheusrules CR with updated changes"
  shell: "oc apply -f /tmp/ksm-alerts.yml --namespace {{ monitoring_upgrade_namespace }}"
  register: apply_prometheusrules
  failed_when: '"prometheusrule.monitoring.coreos.com/ksm-alerts configured" not in apply_prometheusrules.stdout'
