---
managed_service_catalog_data: https://raw.githubusercontent.com/integr8ly/managed-service-controller/v0.0.1/manifests/managed-service-operators.configmap.yaml
managed_service_catalog_source: https://raw.githubusercontent.com/integr8ly/managed-service-controller/v0.0.1/manifests/managed-service-operators.catalogsource.yaml
olm_namespace: kube-system