---
# tasks file for ipaas
-
  name: Download install script
  get_url:
    url: "{{ script_url }}"
    dest: "{{ script_path }}"
    mode: 0644

-
  name: Select openshift project
  shell: oc project {{ namespace }}
  register: project_cmd
  failed_when: false

-
  name: Create openshift project
  shell: oc new-project {{ namespace }}
  when: project_cmd.rc != 0

-
  name: Set user permissions
  shell: oc adm policy add-role-to-user edit {{ username }} -n {{ namespace }}

-
  name: Execute install script
  shell: bash {{ script_path }}
  register: install_cmd
  changed_when: install_cmd.rc == 0
  failed_when: install_cmd.rc != 0

-
  name: Cleanup
  file:
    state: absent
    path: "{{ script_path }}"
