---
# Used to manage images that reference registry.redhat.io which requires authentication
# Pull secret is retrieved from the openshift namespace on a given cluster and can be set in each product namespace to pull images
# Must be overriden for OSD where the pull_secret_name should be set to registry-redhat-io-dockercfg
pull_secret_name: imagestreamsecret