---
- name: Check if namespace exists
  shell: oc get namespace {{ launcher_namespace }}
  ignore_errors: yes
  register: launcher_check_namespace_exists_cmd

- name: Create launcher namespace
  shell: oc new-project {{ launcher_namespace }}
  when: launcher_check_namespace_exists_cmd.rc != 0
