---
# PV backup
- name: Create the enmasse PV CronJob
  include_role:
    name: backup
    tasks_from: _create_backup_cron_job.yml
  vars:
    cronjob_name: "{{ enmasse_pv_cronjob_name }}"
    component: enmasse_pv
    product_name: amqonline

