---
- name: Apply resource overrides for webapp
  include_role:
    name: resource_limits
  vars:
    ns: "{{ webapp_namespace }}"
    resources: "{{ webapp_resources }}"
  when:
    - webapp_resources
    - not webapp_resources is none
    - (webapp_resources | length) > 0
