---
- name: Add additional walkthrough locations in the default list
  set_fact:
    webapp_walkthrough_locations: "{{ webapp_walkthrough_locations + [datasync_walkthrough_location] }}"
  when: datasync | bool | default(true)

- name: Patch webapp walkthrough locations
  shell: oc patch webapp tutorial-web-app-operator -n {{ webapp_namespace }} --type=json -p '[{"op":"replace","path":"/spec/template/parameters/WALKTHROUGH_LOCATIONS","value":"{{ webapp_walkthrough_locations|join(',') }}"}]'
  register: walkthrough_patch_output
  failed_when: walkthrough_patch_output.stderr != ''