---
- name: Get RH-SSO secure route
  shell: oc get route/secure-sso -o template --template \{\{.spec.host\}\} -n {{ rhsso_namespace }}
  register: rhsso_secure_route

- set_fact:
    rhsso_route: "{{ rhsso_secure_route.stdout }}"

- set_fact:
    rhsso_redirect_uri: "{{ openshift_master_url }}"
  when: rhsso_redirect_uri == ""

- import_tasks: admin_token.yml

- name: Generate client template
  template:
    src: "client.json.j2"
    dest: /tmp/client.json

- name: Create public client in {{ rhsso_realm }} realm
  uri:
    url: "https://{{ rhsso_route }}/auth/admin/realms/{{ rhsso_realm }}/clients"
    method: POST
    body: "{{ lookup('file','/tmp/client.json') }}"
    validate_certs: "{{ rhsso_validate_certs }}"
    body_format: json
    headers:
      Authorization: "Bearer {{ rhsso_admin_token }}"
    status_code: [201, 409]

- name: Get client secret
  uri:
    url: "https://{{ rhsso_route }}/auth/admin/realms/{{ rhsso_realm }}/clients/{{ rhsso_client_id }}/client-secret"
    method: GET
    validate_certs: "{{ rhsso_validate_certs }}"
    headers:
      Authorization: "Bearer {{ rhsso_admin_token }}"
    status_code: 200
    return_content: yes
  register: client_config

- name: Store client config locally
  copy:
    content: "{{ client_config }}"
    dest: /tmp/client-config.json

- name: Delete client template file
  file: 
    path: /tmp/client.json
    state: absent
    
