---
- name: Obtain user sso token
  import_tasks: obtain-user-sso-token.yml

- name: Create the walkthroughs realm
  include_tasks: ./create-realm.yml
  with_items:
    - walkthroughs

- name: Create rhmi customer admins and user realms
  include_tasks: ./create-realm.yml
  with_items: "{{ rhsso_seed_users_all | selectattr('admin','match','^(customer|no)$') | map(attribute='username') | list }}"

