---

- name: Import Image Streams
  shell: oc import-image {{ patch_image_stream_item }} --from={{ rhsso_imagestream_image }} --confirm -n openshift
  with_items: "{{ rhsso_user_image_streams }}"
  loop_control:
    loop_var: patch_image_stream_item

- name: Patch Keycloak Operator Deployment
  shell: oc patch deployment keycloak-operator --patch='{"spec":{"template":{"spec":{"containers":[{"name":"keycloak-operator","image":"{{ rhsso_user_operator_image }}"}]}}}}' --namespace {{ rhsso_user_namespace }}
  register: keycloak_operator_image_patch
  failed_when: keycloak_operator_image_patch.stderr

- name: Wait for the new keycloak operator to be ready
  shell: oc rollout status deployment/keycloak-operator -n {{ rhsso_user_namespace }}
  register: rollout_cmd
  failed_when: rollout_cmd.rc != 0
  changed_when: rollout_cmd.rc == 0
