---
# SETUP FUSE ON OPENSHIFT IMAGE STREAMS AND TEMPLATES
- name: Create Fuse on OpenShift image streams
  shell: oc create -f {{ fuse_imagestreams_url }} -n openshift
  register: create_fuse_imagestreams_cmd
  failed_when: create_fuse_imagestreams_cmd.stderr != '' and 'AlreadyExists' not in create_fuse_imagestreams_cmd.stderr

- name: Create Fuse quickstart templates
  shell: oc create -f {{ fuse_templates_url }}/{{ item }} -n openshift
  with_items:
    - "eap-camel-amq-template.json"
    - "eap-camel-cdi-template.json"
    - "eap-camel-cxf-jaxrs-template.json"
    - "eap-camel-cxf-jaxws-template.json"
    - "eap-camel-jpa-template.json"
    - "karaf-camel-amq-template.json"
    - "karaf-camel-log-template.json"
    - "karaf-camel-rest-sql-template.json"
    - "karaf-cxf-rest-template.json"
    - "spring-boot-camel-amq-template.json"
    - "spring-boot-camel-config-template.json"
    - "spring-boot-camel-drools-template.json"
    - "spring-boot-camel-infinispan-template.json"
    - "spring-boot-camel-rest-sql-template.json"
    - "spring-boot-camel-teiid-template.json"
    - "spring-boot-camel-template.json"
    - "spring-boot-camel-xa-template.json"
    - "spring-boot-camel-xml-template.json"
    - "spring-boot-cxf-jaxrs-template.json"
    - "spring-boot-cxf-jaxws-template.json"
  register: create_fuse_quickstart_template_cmd
  failed_when: create_fuse_quickstart_template_cmd.stderr != '' and 'AlreadyExists' not in create_fuse_quickstart_template_cmd.stderr

- name: Create Fuse Console templates
  shell: oc create -f {{ fuse_templates_hawtio_url }}/{{ item }} -n openshift
  with_items:
    - "fis-console-cluster-template.json"
    - "fis-console-namespace-template.json"
  register: create_fuse_console_template_cmd
  failed_when: create_fuse_console_template_cmd.stderr != '' and 'AlreadyExists' not in create_fuse_console_template_cmd.stderr