---
- name: Delete managed service broker resources in {{ msbroker_namespace }}
  shell: "oc process -n {{ msbroker_namespace }} \
  -f {{ msbroker_template }} \
  --param=NAMESPACE={{ msbroker_namespace }} \
  --param=ROUTE_SUFFIX='placeholder' \
  --param=LAUNCHER_DASHBOARD_URL='placeholder' \
  --param=CHE_DASHBOARD_URL='placeholder' \
  --param=THREESCALE_DASHBOARD_URL='placeholder' \
  --param=APICURIO_DASHBOARD_URL='placeholder' \
  --param=IMAGE_ORG={{ msbroker_image_org }} \
  --param=IMAGE_TAG={{ msbroker_release_tag }} \
  --param=SHARED_FUSE_DASHBOARD_URL='placeholder' \
  --param MONITORING_KEY={{ monitoring_key }} | oc delete -n {{ msbroker_namespace }} -f -"
  failed_when: false

- name: "Delete project namespace: {{ msbroker_namespace }}"
  shell: oc delete project {{ msbroker_namespace }}
  register: output
  failed_when: false

- name: "Delete clusterservicebroker namespace: {{ msbroker_namespace }}"
  shell: oc delete clusterservicebroker managed-service-broker
  register: output
  failed_when: false

- name: "Delete clusterrole managed-service"
  shell: oc delete clusterrole managed-service
  register: output
  failed_when: false

- name: Delete CRDs
  shell: "oc delete -f {{ item }}"
  register: output
  failed_when: false
  with_items: "{{ msbroker_required_crds }}"
