---
- name: Delete any previous additionalScrapeConfig secret
  shell: "oc delete secret {{ additional_scrape_config_name }} -n {{ middleware_monitoring_namespace }}"
  failed_when: false

- name: Generate the jobs for the additional scrape config
  template:
    src: "jobs/{{ item }}.j2"
    dest: "/tmp/{{ item }}.yaml"
  with_items: "{{ jobs }}"

- set_fact:
    yaml_files: "{{ jobs | map('regex_replace', '^(.*)$', '/tmp/\\1.yaml') | list }}"

- name: Combine the jobs data
  shell: "awk 'FNR==0{print \"\"}1' {{ yaml_files  | join(' ') }}"
  register: jobs_data

- name: Create additional scrape config secret with combined jobs as value
  shell: "oc create secret generic {{ additional_scrape_config_name }} --from-literal={{ secret_key }}='{{ jobs_data.stdout }}' -n {{ middleware_monitoring_namespace }}"

- name: Patch the Prometheus custom resource with the additional scrape config secret details
  shell: "oc patch --type merge prometheus {{ prometheus_cr_name }} --patch '{{ additional_scrape_config_patch | to_json }}' -n {{ middleware_monitoring_namespace }}"
  register: prometheus_patch
  failed_when: prometheus_patch.stderr != '' and 'not patched' not in prometheus_patch.stderr
  changed_when: prometheus_patch.rc == 0

- name: Delete the temp yaml files
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ yaml_files }}"