---
- hosts: master
  gather_facts: no
  tasks:
    - include_role:
        name: webapp
        tasks_from: cors
      tags: ['webapp', 'remote']
    - include_role:
        name: rhsso
        tasks_from: identityprovider
      vars:
        rhsso_openshift_master_config_path: "{{ eval_openshift_master_config_path }}"
      tags: ['rhsso', 'remote']
