---
- hosts: master
  gather_facts: no
  tasks:
    - block:
      -
        name: Retrieve master configurations
        slurp:
          src: "{{ eval_openshift_master_config_path }}"
        register: eval_master_config
        become: yes
      -
        add_host:
          name: EVAL_VARS
          eval_app_host: "{{ (eval_master_config['content'] | b64decode | from_yaml)['routingConfig']['subdomain'] }}"
          openshift_master_url: "{{ (eval_master_config['content'] | b64decode | from_yaml)['masterPublicURL'] }}"
      tags: ['bootstrap', 'remote']

- import_playbook: "./openshift.yml"
- import_playbook: "./install_sso.yml"
- import_playbook: "./install_infra.yml"
- import_playbook: "./install_services.yml"
- import_playbook: "./install_fuse_managed.yml"
- import_playbook: "./install_webapp.yml"
- import_playbook: "./install_middleware_monitoring.yml"
- import_playbook: "./install_kube_state_metrics.yml"
- import_playbook: "./generate-customisation-inventory.yml"
