---
- hosts: master
  gather_facts: no
  tasks:
    - name: generate admin password
      set_fact:
        adminPass: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"

    - name: Create integreatly-admin user
      shell: htpasswd -b /etc/origin/master/htpasswd integreatly-admin {{adminPass}}
      register: user_cmd
      failed_when: user_cmd.rc != 0

    - name: Give integreatly-admin user cluster admin
      shell: oc adm policy add-cluster-role-to-user integreatly-admin clusteradmin
      register: oc_cmd
      failed_when: oc_cmd.rc != 0

    - block:
      -
        name: Retrieve master configurations
        slurp:
          src: "{{ eval_openshift_master_config_path }}"
        register: eval_master_config
        become: yes
      -
        add_host:
          name: EVAL_VARS
          eval_app_host: "{{ (eval_master_config['content'] | b64decode | from_yaml)['routingConfig']['subdomain'] }}"
          openshift_master_url: "{{ (eval_master_config['content'] | b64decode | from_yaml)['masterPublicURL'] }}"
      tags: ['bootstrap', 'remote']

- import_playbook: "./openshift.yml"
- import_playbook: "./install_sso.yml"
- import_playbook: "./install_infra.yml"
- import_playbook: "./install_services.yml"
- import_playbook: "./install_webapp.yml"
- import_playbook: "./install_middleware_monitoring.yml"
- import_playbook: "./install_kube_state_metrics.yml"
- import_playbook: "./generate-customisation-inventory.yml"

- hosts: localhost
  gather_facts: no
  tasks:
    - debug:
        msg: All services have been provisioned successfully.
    - debug:
        msg: Please add '{{ callback_url }}' as the Authorization callback URL of your GitHub OAuth Application.
      vars:
        callback_url: "{{ launcher_sso_route }}/auth/realms/{{ eval_launcher_sso_realm }}/broker/github/endpoint"
      when: launcher

