---
- name: Create monitoring namespace
  shell: "oc new-project {{ monitoring_namespace }}"
  register: monitoring_namespace_create
  until: monitoring_namespace_create.stderr == '' or 'AlreadyExists' in monitoring_namespace_create.stderr
  retries: 50
  delay: 10
  failed_when: false
  changed_when: false

- name: Add monitoring label to namespace
  shell: oc patch ns {{ monitoring_namespace }} --patch '{"metadata":{"labels":{"{{ monitoring_label_name }}":"{{ monitoring_label_value }}"}}}'

- include: ./create_resource_from_template.yml
  with_items: "{{ monitoring_resource_templates }}"

- name: Create required operator resources
  shell: "oc apply -f {{ item }} -n {{ monitoring_namespace }}"
  register: monitoring_resource_create
  with_items: "{{ monitoring_resources }}"
