---

- include_role:
    name: namespace
    tasks_from: create
  vars:
    name: "{{ che_namespace }}"
    display_name: "{{ che_display_name }}"
    monitor: true
    is_service: true

- include_tasks: install.yml

- name: Include keycloak tasks
  include_tasks: keycloak-client.yml
  when: che_multiuser|bool == true
