- name: Extract CodeReady CLI version 2.0.0 to the temp directory
  unarchive:
    src: crwctl.tar.gz
    dest: /tmp

- name: Run the CodeReady CLI upgrade command
  shell: /tmp/crwctl/bin/crwctl server:update -n {{ che_namespace }} --skip-version-check

- name: Remove the temp directory
  file:
    path: /tmp/crwctl
    state: absent