webapp_template: https://raw.githubusercontent.com/integr8ly/tutorial-web-app/development/deployment/openshift-template.yml
webapp_namespace: webapp
webapp_client_id: tutorial-web-app
webapp_route: tutorial-web-app

openshift_master_config_path: /etc/origin/master/master-config.yaml