---
- name: Apply resource overrides for fuse
  include_role:
    name: resource_limits
  vars:
    ns: "{{ fuse_namespace }}"
    resources: "{{ fuse_resources }}"
  when:
    - fuse_resources
    - not fuse_resources is none
    - (fuse_resources | length) > 0
