---
rhsso_user_tmp_dir: /tmp
rhsso_user_namespace: "{{ eval_user_rhsso_namespace | default('user-sso') }}"
rhsso_user_rbac_name: mdc-account-keycloak-operator
rhsso_user_client_id: user-sso

rhsso_user_resources:
  - name: sso
    kind: dc
    resources:
      requests:
        memory: 500Mi
    replicas: 2
  - name: sso-postgresql
    kind: dc
    resources:
      requests:
        memory: 25Mi

rhsso_user_operator_image: "quay.io/integreatly/keycloak-operator:{{ rhsso_operator_release_tag }}"

rhsso_user_image_streams:
  - "{{ rhsso_imagestream_name }}"