---
- name: Apply resource overrides for launcher
  include_role:
    name: resource_limits
  vars:
    ns: "{{ launcher_namespace }}"
    resources: "{{ launcher_resources }}"
  when:
    - launcher_resources
    - not launcher_resources is none
    - (launcher_resources | length) > 0
