ups_namespace: "{{ eval_ups_namespace | default('mobile-unifiedpush') }}"
ups_resources_list:
  - "{{ ups_operator_resources }}/service_account.yaml"
  - "{{ ups_operator_resources }}/role.yaml"
  - "{{ ups_operator_resources }}/crds/push_v1alpha1_unifiedpushserver_crd.yaml"
ups_operator_deployment: "{{ ups_operator_resources }}/operator.yaml"
ups_template_dir: /tmp
ups_server_name: unifiedpush

#backup
ups_backup: "{{ backup_restore_install | default(false) }}"
ups_backup_name: ups-daily-at-midnight
ups_backup_schedule: "{{ backup_schedule }}"
ups_backup_secret: "s3-credentials"
ups_backup_secret_namespace: "{{ backup_namespace }}"
ups_encryption_secret: ''
ups_encryption_secret_namespace: "{{ backup_namespace }}"

#monitor
ups_message_broker: false

#scaling
ups_resources: []
