---
- name: "Create 3scale namespace: {{ threescale_namespace }}"
  shell: oc new-project {{ threescale_namespace }}
  register: threescale_namespace_exists
  failed_when: threescale_namespace_exists.stderr != '' and 'already exists' not in threescale_namespace_exists.stderr
  changed_when: threescale_namespace_exists.rc == 0

- import_tasks: resources.yml
- import_tasks: sso.yml
- import_tasks: routes.yml

- name: Generate operator template files
  template:
    src: "{{ item }}.j2"
    dest: /tmp/{{ item }}
  with_items:
    - rbac.yaml
    - crd.yaml
    - cr.yaml
    - operator.yaml

- name: Deploy operator resources
  shell: "oc apply -f /tmp/{{ item }} -n {{ threescale_namespace }}"
  with_items:
    - rbac.yaml
    - crd.yaml
    - cr.yaml
    - operator.yaml

- name: "Verify 3Scale deployment succeeded"
  shell: sleep 5; oc get threescale/3scale -o template --template \{\{.status.ready\}\} --namespace {{ threescale_namespace }}  |  grep  true
  register: result
  until: result.stdout
  retries: 50
  delay: 10
  failed_when: not result.stdout
  changed_when: False
