---
- name: Apply resource overrides for enmasse
  include_role:
    name: resource_limits
  vars:
    ns: "{{ mobile_security_service_namespace }}"
    resources: "{{ mobile_security_service_resources }}"
  when: (mobile_security_service_resources | d([], true) | length) > 0
