-
  name: Check if che pvc is created
  shell: "oc get pvc/che-data-volume -n {{ che_namespace }}"
  register: che_pvc_cmd
  failed_when: false

-
  name: Create che persistent volume
  shell: oc apply -f {{ che_template_folder }}/pvc/che-server-pvc.yaml
  when: che_pvc_cmd.rc != 0

-
  name: Check if dc has volume config
  shell: "oc get dc/che -o jsonpath='{.spec.template.spec.containers[0].volumeMounts[0].name}' -n {{ che_namespace }}"
  register: che_dc_pv_cmd
  failed_when: false

-
  name: Set che pod persistent volume
  shell: oc set volume dc/che --add -m /data --name=che-data-volume --claim-name=che-data-volume
  when: che_dc_pv_cmd.stdout != 'che-data-volume'

-
  name: "Verify che server pv deployment succeeded"
  shell: sleep 5; oc get pods --namespace {{ che_namespace }}  |  grep  "deploy"
  register: result
  until: not result.stdout
  retries: 50
  delay: 10
  failed_when: result.stdout
  changed_when: False
