---
- name: Create AMQ ImageStream
  shell: oc create -n {{ amq_template_namespace }} -f {{ amq_imagestream }}
  register: cmd_amq_imagestream
  failed_when: cmd_amq_imagestream.stderr != '' and 'already exists' not in cmd_amq_imagestream.stderr
  changed_when: cmd_amq_imagestream.rc == 0

- name: Create AMQ Template
  shell: oc create -n {{ amq_template_namespace }} -f {{ amq_template }}
  register: cmd_amq_template
  failed_when: cmd_amq_template.stderr != '' and 'already exists' not in cmd_amq_imagestream.stderr
  changed_when: cmd_amq_template.rc == 0
