---
- name: Delete AMQ ImageStreams
  shell: oc delete -n {{ amq_template_namespace }} -f {{ item }}
  register: cmd_amq_imagestream
  failed_when: cmd_amq_imagestream.stderr != '' and 'not found' not in cmd_amq_imagestream.stderr
  changed_when: cmd_amq_imagestream.rc == 0
  with_items: "{{amq_imagestreams}}"

- name: Delete AMQ Template
  shell: oc delete -n {{ amq_template_namespace }} -f {{ item }}
  register: cmd_amq_template
  failed_when: cmd_amq_template.stderr != '' and 'not found' not in cmd_amq_template.stderr
  changed_when: cmd_amq_template.rc == 0
  with_items: "{{amq_templates}}"
