---
# Remove walkthrough apps from the catalog
- name: Remove crud spring boot app from the catalog
  command: oc delete template/spring-boot-rest-http-crud -n openshift
  register: output
  failed_when: output.stderr != '' and 'not found' not in output.stderr
  changed_when: output.rc == 0
  
- name: Remove location soap app from the catalog
  command: oc delete template/location-soap -n openshift
  register: output
  failed_when: output.stderr != '' and 'not found' not in output.stderr
  changed_when: output.rc == 0

- name: Remove messaging work queue nodejs from the catalog
  command: oc delete template/nodejs-messaging-work-queue-frontend -n openshift
  register: output
  failed_when: output.stderr != '' and 'not found' not in output.stderr
  changed_when: output.rc == 0

- name: Remove messaging nodejs order entry UI from the catalog
  command: oc delete template/rhmi-lab-nodejs-order-ui -n openshift
  register: output
  failed_when: output.stderr != '' and 'not found' not in output.stderr
  changed_when: output.rc == 0

- name: Remove messaging nodejs order management UI from the catalog
  command: oc delete template/rhmi-lab-order-management-ui -n openshift
  register: output
  failed_when: output.stderr != '' and 'not found' not in output.stderr
  changed_when: output.rc == 0

- name: Remove messaging camel/fuse order API from the catalog
  command: oc delete template/rhmi-lab-fuse-internal-orders-api -n openshift
  register: output
  failed_when: output.stderr != '' and 'not found' not in output.stderr
  changed_when: output.rc == 0
