---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Check current version
      shell: "oc get secret manifest -n {{ eval_webapp_namespace }} -o json | jq \".data.generated_manifest\" -r | base64 -d | jq \".version\" -r"
      register: version

    - fail:
        msg: "The current installation could not be verified as the manifest could not be read"
      when: version.stderr != ""
    - fail:
        msg: "The installed version must be 1.3.0 to run this upgrade playbook, {{ version.stdout }} is currently installed"
      when: version.stdout != "release-1.3.0"


    - name: Update keycloak-operator image tag
      shell: "oc patch deployment keycloak-operator -n {{ eval_rhsso_namespace }} --type json -p '[{\"op\": \"replace\", \"path\": \"/spec/template/spec/containers/0/image\", \"value\": \"quay.io/integreatly/keycloak-operator:v1.3.4\"}]'"


    - name: add CreateOnly to openshift keycloak realm
      shell: "oc patch keycloakrealm openshift -n {{ eval_rhsso_namespace }} --type json -p '[{\"op\": \"add\", \"path\": \"/spec/createOnly\", \"value\": true}]'"