---
- name: "Create directory if it doesn't exist"
  file:
    path: "/tmp/enmasse-artifacts/"
    state: directory

- name: "Download and unpack EnMasse {{ enmasse_release }} artifact"
  unarchive:
    src: "{{ enmasse_release_artifacts[enmasse_release]['url'] }}"
    dest: "/tmp/enmasse-artifacts/"
    extra_opts: [--strip-components=1]
    remote_src: yes

- name: "Copy custom EnMasse playbook into unpacked Ansible project"
  copy:
    src: "{{ role_path }}/files/enmasse-playbook.yml"
    dest: "/tmp/enmasse-artifacts/ansible/playbooks/openshift/"
    remote_src: yes
