# https://issues.jboss.org/browse/INTLY-521

- copy:
    src: patch-keycloak-strategy.json
    dest: /tmp/patch-keycloak-strategy.json

- name: Store contents of the keycloak deployment strategy patch
  shell: cat /tmp/patch-keycloak-strategy.json
  register: strategy_patch

- name: "Patch keycloak-controller strategy"
  shell: oc patch deployment/keycloak-controller -p '{{ strategy_patch.stdout }}' -n {{ enmasse_namespace }}

- name: "Patch keycloak strategy"
  shell: oc patch deployment/keycloak -p '{{ strategy_patch.stdout }}' -n {{ enmasse_namespace }}