---
- name: Check that enmasse cluster service broker exists
  shell: kubectl api-resources --api-group="servicecatalog.k8s.io" -o=name | grep clusterservicebrokers
  register: result
  changed_when: false
  failed_when: false
  
- name: "Delete enmasse cluster service broker"
  shell: oc delete clusterservicebroker enmasse
  register: output
  when: result.rc == 0
  failed_when: output.stderr != '' and 'not found' not in output.stderr and "the server doesn't have a resource type" not in output.stderr

- name: Get enmasse apiServices
  shell: for i in $(oc get apiServices | grep enmasse | awk '{ print $1}');do echo "$i"; done
  register: api_services_output

- name: "Delete enmasse apiServices"
  shell: "oc delete apiservice {{ item }}"
  with_items: "{{ api_services_output.stdout_lines }}"

- name: "Delete project namespace: {{ enmasse_namespace | default('enmasse') }} "
  shell: "oc delete project {{ enmasse_namespace | default('enmasse')}} "
  register: output
  failed_when: output.stderr != '' and 'not found' not in output.stderr and 'The system is ensuring all content is removed from this namespace.' not in output.stderr
  changed_when: output.rc == 0
