apiVersion: v1
kind: Template
metadata:
  name: rhmi-lab-nodejs-order-ui
  annotations:
    iconClass: icon-jboss
    tags: nodejs, microservice, messaging
    template.openshift.io/provider-display-name: "Red Hat, Inc."
    description: The Node.js Work Queue Mission demonstrates scalable task processing using messaging
parameters:
  - name: MESSAGING_SERVICE_NAME
    description: Name of the messaging service
    displayName: Messaging service name
    value: '{{ msg_work_queue_node_service_name }}'
    required: true

  - name: MESSAGING_SERVICE_HOST
    description: Host of messaging service
    displayName: Messaging service
    value: '{{ msg_work_queue_node_service_host }}'
    required: true

  - name: MESSAGING_SERVICE_PORT
    description: Port used by the messaging service
    displayName: Messaging service port
    value: '{{ msg_work_queue_node_service_port }}'
    required: true

  - name: MESSAGING_SERVICE_USER
    description: User used to log into the messaging service 
    displayName: Messaging service user
    value: '{{ msg_work_queue_node_service_user }}'
    required: true

  - name: MESSAGING_SERVICE_PASSWORD
    description: Password used to log into the messaging service
    displayName: Messaging service password
    value: '{{ msg_work_queue_node_service_password }}'
    required: true

objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: {{ msg_work_queue_node_service_name }}
  data:
    MESSAGING_SERVICE_HOST: ${MESSAGING_SERVICE_HOST}
    MESSAGING_SERVICE_PORT: ${MESSAGING_SERVICE_PORT}
    MESSAGING_SERVICE_USER: ${MESSAGING_SERVICE_USER}
    MESSAGING_SERVICE_PASSWORD: ${MESSAGING_SERVICE_PASSWORD}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: rhmi-lab-nodejs-order-ui
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: runtime-rhmi-lab-nodejs-order-ui
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: bucharestgold/centos7-s2i-nodejs:10.x
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: rhmi-lab-nodejs-order-ui
    name: rhmi-lab-nodejs-order-ui
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: rhmi-lab-nodejs-order-ui
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        labels:
          app: rhmi-lab-nodejs-order-ui
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          envFrom:
          - configMapRef:
              name: messaging-service
          image: quay.io/integreatly/rhmi-lab-nodejs-order-frontend:{{ msg_work_queue_node_image_tag }}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /api/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
          name: rhmi-lab-nodejs-order-ui
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /api/health/readiness
              port: 8080
              scheme: HTTP
          securityContext:
            privileged: false
      metadata:
        labels:
          app: rhmi-lab-nodejs-order-ui
    triggers:
    - type: ConfigChange
      imageChangeParams:
        automatic: true
        containerNames:
        - rhmi-lab-nodejs-order-ui
        from:
          kind: ImageStreamTag
          name: rhmi-lab-nodejs-order-ui:latest
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: rhmi-lab-nodejs-order-ui
    name: rhmi-lab-nodejs-order-ui
  spec:
    ports:
    - name: http
      port: 8080
    selector:
      app: rhmi-lab-nodejs-order-ui
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: rhmi-lab-nodejs-order-ui
    name: frontend
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: rhmi-lab-nodejs-order-ui
