---
-
  name: "check keycloak namespace exists"
  shell: "oc get project {{ eval_rhsso_namespace }} | grep {{ eval_rhsso_namespace }} | wc -l"
  register: "sso_namespace_exists"

- name: Create ServiceAccount and role binding
  include_role:
    name: backup
    tasks_from: _setup_service_account.yml
  vars:
    binding_name: rhsso-backup-binding
    serviceaccount_namespace: '{{ eval_rhsso_namespace }}'

-
  name: "Add backups to keycloak CR"
  when: sso_namespace_exists.stdout != "0"
  block:
    -
      name: "patch Keycloak CR"
      shell: oc patch keycloak rhsso -n {{ eval_rhsso_namespace }} --patch '{"spec":{"backups":{{ rhsso_backups | to_json }}}}' --type=merge

