---

- name: "check for aws credentials secret in {{backup_credentials_ns}} namespace"
  shell: "oc get secret {{backup_credentials_secret}} -n {{backup_credentials_ns}}"
  register: secret_cmd
  failed_when: output.stderr != '' and 'not found' not in output.stderr
  changed_when: oc.rc == 0

- name: "Create backup cron jobs"
  debug:
    msg: "{{item[0]}}  {{item[1]}}"
  with_nested:
    - "{{backed_up_product_namespaces}}"
    - "{{backup_resources}}"