- import_playbook: "./prerequisites.yml"
- import_playbook: "./openshift.yml"

- hosts: localhost
  tasks:
    - include_vars: ../roles/ups/defaults/main.yml
    - include_vars: ../roles/mdc/defaults/main.yml

    - name: Retrieve current manifest
      shell: "oc get secret/manifest -o jsonpath='{.data.generated_manifest}' -n {{ eval_webapp_namespace }}"
      register: webapp_secret_cmd

    - name: Decode webapp secret
      set_fact:
        webapp_manifest: "{{ webapp_secret_cmd.stdout | b64decode | from_json }}"

    - set_fact:
        mobile_components: []

    #unified push server(ups)
    - name: Unified Push Server
      block:
        - name: Get Unified Push Server route
          shell: oc get route/unifiedpush-unifiedpush-proxy  -o template --template \{\{.spec.host\}\} -n {{ eval_ups_namespace | default('unifiedpush') }}
          register: ups_route_cmd
        - set_fact:
            ups_route: "https://{{ups_route_cmd.stdout}}"
        - name: Set Unified Push Server component
          set_fact:
            ups_manifest:
              - name: Unified Push Server
                version: "{{ ups_release_tag }}"
                host: "{{ ups_route }}"
                mobile: true
                type: "push"
        - set_fact:
            mobile_components: "{{ mobile_components }} + {{ ups_manifest }}"
      when: ups | default(true) | bool

    # mobile developer console (mdc)
    - name: Mobile Developer Console
      block:
        - name: Get mdc secure route
          shell: "oc get route/mdc-mdc-proxy -o jsonpath='{.spec.host}' -n {{ mdc_namespace }}"
          register: mdc_route_cmd
        - set_fact:
            mdc_route: "https://{{mdc_route_cmd.stdout}}"
        - name: Set Mobile Developer Console component
          set_fact:
            mdc_manifest:
              - name: Mobile Developer Console
                version: "{{ mdc_release_tag }}"
                host: "{{ mdc_route }}"
        - set_fact:
            mobile_components: "{{ mobile_components }} + {{ mdc_manifest }}"
      when: mdc | default(true) | bool

    - name: Add mobile items to manifest definition
      manifest_add:
        manifest: "{{ webapp_manifest }}"
        items: "{{ mobile_components }}"
      register: manifest_add_out

    - name: Write config to file
      copy:
        content: "{{ manifest_add_out.manifest | to_nice_json }}"
        dest: "/tmp/mobile-manifest.json"

    - name: Create manifest file in webapp namespace
      block:
        - name: Check if manifest secret exists
          shell: oc get secret manifest -n {{ eval_webapp_namespace }}
          register: manifest_secret
          failed_when: manifest_secret.stderr != '' and 'NotFound' not in manifest_secret.stderr

        - name: Delete secret if it exists
          shell: oc delete secret manifest -n {{ eval_webapp_namespace }}
          when: manifest_secret.stderr == ""

        - name: Create manifest secret
          shell: oc create secret generic manifest --from-file=generated_manifest=/tmp/mobile-manifest.json --type=application/json -n {{ eval_webapp_namespace }}

    - name: Create manifest file in mdc namespace
      block:
        - name: Check if manifest secret exists
          shell: oc get secret manifest -n {{ mdc_namespace }}
          register: manifest_secret
          failed_when: manifest_secret.stderr != '' and 'NotFound' not in manifest_secret.stderr

        - name: Delete secret if it exists
          shell: oc delete secret manifest -n {{ mdc_namespace }}
          when: manifest_secret.stderr == ""

        - name: Create manifest secret
          shell: oc create secret generic manifest --from-file=generated_manifest=/tmp/mobile-manifest.json --type=application/json -n {{ mdc_namespace }}
      when: mdc | default(true) | bool

    - include_role:
        name: mdc
        tasks_from: patch-manifest.yml
      vars:
        mdc_manifest_secret_name: manifest
      tags: ['mdc']
      when:
        - mdc | default(true) | bool
