
- name: Check console-config namespace exists
  shell: oc get namespace console-config
  register: console_config_check_namespace_exists
  failed_when: false

- name: "Get route to hosted javascript file"
  shell: oc get route {{ customise_web_console.route_name }} -n {{ customise_web_console.namespace }} --template '{{ "{{" }}printf "https://%s\n" .spec.host{{ "}}" }}'
  register: get_javascript_route
  failed_when: get_javascript_route.stderr != ""
  when: console_config_check_namespace_exists.rc == 0

- name: "download current openshift web console configmap"
  shell: oc get configmap {{ customise_web_console.web_console.configmap }} -n {{ customise_web_console.web_console.namespace }} --template '{{ "{{" }} index .data "{{ customise_web_console.web_console.configmap_key -}}" {{ "}}" }}'
  register: get_web_console_config_result
  failed_when: get_web_console_config_result.stderr != ""

- name: "Rewrite console configmap"
  when: get_javascript_route.stdout + '/' + customise_web_console.javascript_filename in get_web_console_config_result.stdout
  block:

    - name: "determine changes needed to remove script url from web console config"
      shell: echo '{{ get_web_console_config_result.stdout | from_yaml | to_nice_json}}' | jq 'walk( if type == "array" then map(select(. != "{{ get_javascript_route.stdout }}/{{ customise_web_console.javascript_filename }}")) else . end )'
      register: new_web_console_config_json_result

    - name: "write patched web console config to file"
      copy: content={{ new_web_console_config_json_result.stdout | from_json | to_nice_yaml(indent=2) }} dest=/tmp/{{ customise_web_console.web_console.configmap_key }}

    - name: "update {{ customise_web_console.web_console.namespace }}/{{ customise_web_console.web_console.configmap }} configmap"
      shell: oc create configmap {{ customise_web_console.web_console.configmap }} --from-file=/tmp/{{ customise_web_console.web_console.configmap_key }} -n {{ customise_web_console.web_console.namespace }} --dry-run -o yaml | oc replace -f -

- name: "Delete {{ customise_web_console.namespace }} namespace"
  shell: "oc delete namespace {{ customise_web_console.namespace }}"
  register: output
  failed_when: output.stderr != '' and 'not found' not in output.stderr and 'The system is ensuring all content is removed from this namespace.' not in output.stderr
  changed_when: output.rc == 0
  when: console_config_check_namespace_exists.rc == 0
