apicurito_namespace: "{{ns_prefix | default('')}}apicurito"
apicurito_display_name: "Apicurito"
apicurito_template: apicurito
apicurito_template_namespace: openshift
apicurito_template_file: /tmp/apicurito-template.yaml
apicurito_template_file_format: yaml
apicurito_route_hostname: apicurito-app


apicurito_resources:
  - name: apicurito-ui
    kind: dc
    resources: 
      limits: 
        cpu: 1
        memory: 256Mi
      requests: 
        cpu: 200m
        memory: 64Mi
  # - name: fuse-apicurito-generator
  #   kind: dc
  #   resources: 
  #     limits: 
  #       cpu: 1
  #       memory: 256Mi
  #     requests: 
  #       cpu: 200m
  #       memory: 64Mi
  - name: missing-resource
    kind: dc
    resources:
      requests:
        memory: 20M
  - name: name-is-irrelevant 
    kind: bad-kind
    resources:
      - container: xyz
        requests:
          memory: 20M
